{% set name = "pycuda" %}
{% set version = "2019.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ada56ce98a41f9f95fe18809f38afbae473a5c62d346cfa126a2d5477f24cc8a

build:
  number: 0
  skip: True  # [win or osx]
  script:
    - export CUDA_INC_DIR=/usr/local/cuda
    - {{ PYTHON }} configure.py --cuda-root=/usr/local/cuda
    - {{ PYTHON }} -m pip install . -vv --install-option=--enable-cuda

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
  host:
    - numpy >=1.6
    - pip
    - python

  run:
    - appdirs >=1.4.0
    - decorator >=3.2.0
    - mako
    - python
    - pytools >=2011.2
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pycuda
    - pycuda.compyte

about:
  home: https://pypi.org/project/pycuda/
  summary: Python wrapper for Nvidia CUDA
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/inducer/pycuda

extra:
  recipe-maintainers:
    - rluria14
    - oblute
    - ndmaxar
